# Build
# docker build -t mywalletapp-backend:1.0.0 -f DockerFile .
# RUN
# docker run -p 3800:3800 mywalletapp-backend:1.0.0

FROM node:14.18.0

ENV POSTGRES_USER=postgres \
    POSTGRES_PASSWORD=admin01 \
    POSTGRES_HOST=localhost \
    POSTGRES_DATABASE=postgres \
    POSTGRES_PORT=5434

COPY . /opt/mywalletapp-backend

WORKDIR /opt/mywalletapp-backend

RUN npm install

EXPOSE 3800

CMD ["npm","start"]